MDScreen:

    MDBoxLayout:
        orientation: "vertical"
        spacing: "12dp"
        padding: "16dp"

        HeaderCard:

        ScrollView:
            do_scroll_x: False

            MDBoxLayout:
                orientation: "vertical"
                adaptive_height: True
                spacing: "16dp"
                padding: "8dp"

                InputCard:
                    id: input_card

                ResultCard:
                    id: result_card